version: "3.8"
services: 
    backend:
        build: 
            context: .
            dockerfile: ./Dockerfile
        container_name: django
        command: >
          sh -c "
            python manage.py makemigrations
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        environment:
          - API_KEY=${API_KEY}
          - REDIS_URL=${REDIS_URL}
        volumes:
          - .:/api/
        depends_on:
          - redis
    redis:
      image: redis:alpine
      ports:
        - "6379:6379"
    celery:
      restart: always
      build:
        context: .
      command: celery -A conf worker -B -l info
      volumes:
        - .:/api/
      depends_on:
        - redis